// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolPredict.Api.Infrastructure.Persistence;

#nullable disable

namespace PoolPredict.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PoolPredictDbContext))]
    [Migration("20260601085230_Sprint5MarketSettlementFoundation")]
    partial class Sprint5MarketSettlementFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AwayParticipant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("away_participant");

                    b.Property<Guid>("AwayParticipantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("away_participant_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("HomeParticipant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("home_participant");

                    b.Property<Guid>("HomeParticipantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("home_participant_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("StartsAt");

                    b.HasIndex("TournamentId", "ExternalId")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<decimal?>("LineValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("line_value");

                    b.Property<int>("PayoutConfigurationVersion")
                        .HasColumnType("int")
                        .HasColumnName("payout_configuration_version");

                    b.Property<decimal>("PayoutMultiplier")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("payout_multiplier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("period");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PoolId");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("country");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "ExternalId")
                        .IsUnique();

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("payout_configurations", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutMarketRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<decimal?>("LineValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("line_value");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("market_type");

                    b.Property<Guid>("PayoutConfigurationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payout_configuration_id");

                    b.Property<decimal>("PayoutMultiplier")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("payout_multiplier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("period");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("profile");

                    b.HasKey("Id");

                    b.HasIndex("PayoutConfigurationId", "Profile", "MarketType", "Period")
                        .IsUnique();

                    b.ToTable("payout_configuration_market_rules", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPointLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<Guid?>("PredictionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("prediction_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("MemberId", "CreatedAt");

                    b.ToTable("point_ledger", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("profile");

                    b.Property<int>("StartingBalance")
                        .HasColumnType("int")
                        .HasColumnName("starting_balance");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("pools", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPoolInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pool_invites", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPoolMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PoolId", "UserId")
                        .IsUnique();

                    b.ToTable("pool_members", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal?>("LineValueSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("line_value_snapshot");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("char(36)")
                        .HasColumnName("market_id");

                    b.Property<string>("MarketPeriod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("market_period");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("market_type");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<int>("PayoutConfigurationVersionSnapshot")
                        .HasColumnType("int")
                        .HasColumnName("payout_configuration_version_snapshot");

                    b.Property<decimal>("PayoutMultiplierSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("payout_multiplier_snapshot");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("selected_option");

                    b.Property<int>("Stake")
                        .HasColumnType("int")
                        .HasColumnName("stake");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PoolId");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<Guid?>("PredictionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("prediction_id");

                    b.Property<Guid>("SettlementRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("settlement_run_id");

                    b.HasKey("Id");

                    b.HasIndex("SettlementRunId");

                    b.ToTable("settlement_logs", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("settlement_runs", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedTournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("sport");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedUserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutMarketRule", b =>
                {
                    b.HasOne("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutConfiguration", "PayoutConfiguration")
                        .WithMany("Rules")
                        .HasForeignKey("PayoutConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayoutConfiguration");
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementLog", b =>
                {
                    b.HasOne("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementRun", "SettlementRun")
                        .WithMany("Logs")
                        .HasForeignKey("SettlementRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementRun");
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutConfiguration", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementRun", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
