// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolPredict.Api.Infrastructure.Persistence;

#nullable disable

namespace PoolPredict.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PoolPredictDbContext))]
    [Migration("20260618063759_DatabaseBackupEmailSettings")]
    partial class DatabaseBackupEmailSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedEmailSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BackupLastSentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("backup_last_sent_at");

                    b.Property<string>("BackupToEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("backup_to_email");

                    b.Property<DateTimeOffset?>("BackupUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("backup_updated_at");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("from_email");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("from_name");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("host");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseStartTls")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("use_start_tls");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("email_settings", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AwayParticipant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("away_participant");

                    b.Property<Guid>("AwayParticipantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("away_participant_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("HomeParticipant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("home_participant");

                    b.Property<Guid>("HomeParticipantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("home_participant_id");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_test_data");

                    b.Property<string>("ManagementMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("management_mode");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("StartsAt");

                    b.HasIndex("TournamentId", "Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedEventResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<int?>("FirstHalfAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("first_half_away_score");

                    b.Property<int?>("FirstHalfHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("first_half_home_score");

                    b.Property<int>("FullTimeAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("full_time_away_score");

                    b.Property<int>("FullTimeHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("full_time_home_score");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_results", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedIdentityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Purpose", "TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Purpose", "ConsumedAt");

                    b.ToTable("identity_tokens", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<decimal?>("LineValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("line_value");

                    b.Property<int>("PayoutConfigurationVersion")
                        .HasColumnType("int")
                        .HasColumnName("payout_configuration_version");

                    b.Property<decimal>("PayoutMultiplier")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("payout_multiplier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("period");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PoolId");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("country");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_test_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("payout_configurations", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutMarketRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<decimal?>("LineValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("line_value");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("market_type");

                    b.Property<Guid>("PayoutConfigurationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payout_configuration_id");

                    b.Property<decimal>("PayoutMultiplier")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("payout_multiplier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("period");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("profile");

                    b.HasKey("Id");

                    b.HasIndex("PayoutConfigurationId", "Profile", "MarketType", "Period")
                        .IsUnique();

                    b.ToTable("payout_configuration_market_rules", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPointLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<Guid?>("PredictionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("prediction_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("MemberId", "CreatedAt");

                    b.ToTable("point_ledger", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnnouncementTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("announcement_title");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("cover_image_url");

                    b.Property<int>("DefaultStake")
                        .HasColumnType("int")
                        .HasColumnName("default_stake");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hidden");

                    b.Property<decimal>("LeaderboardMinEventAverageStakePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("leaderboard_min_event_average_stake_percent");

                    b.Property<int>("MaxStake")
                        .HasColumnType("int")
                        .HasColumnName("max_stake");

                    b.Property<int>("MaxTotalStakePerEvent")
                        .HasColumnType("int")
                        .HasColumnName("max_total_stake_per_event");

                    b.Property<int>("MinStake")
                        .HasColumnType("int")
                        .HasColumnName("min_stake");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_user_id");

                    b.Property<bool>("PredictionsLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("predictions_locked");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("profile");

                    b.Property<int>("StartingBalance")
                        .HasColumnType("int")
                        .HasColumnName("starting_balance");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("pools", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPoolInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("revoked_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pool_invites", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPoolJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PoolId", "UserId")
                        .IsUnique();

                    b.ToTable("pool_join_requests", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPoolMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<string>("LeaderboardStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("leaderboard_status");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<int>("VipAdjustmentAmount")
                        .HasColumnType("int")
                        .HasColumnName("vip_adjustment_amount");

                    b.HasKey("Id");

                    b.HasIndex("PoolId", "UserId")
                        .IsUnique();

                    b.ToTable("pool_members", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPoolMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int?>("AnnouncementSlot")
                        .HasColumnType("int")
                        .HasColumnName("announcement_slot");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("author_member_id");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("body_markdown");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("kind");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorMemberId");

                    b.HasIndex("PoolId", "CreatedAt");

                    b.HasIndex("PoolId", "Kind", "AnnouncementSlot")
                        .IsUnique();

                    b.ToTable("pool_messages", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal?>("LineValueSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("line_value_snapshot");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("char(36)")
                        .HasColumnName("market_id");

                    b.Property<string>("MarketPeriod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("market_period");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("market_type");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<int>("PayoutConfigurationVersionSnapshot")
                        .HasColumnType("int")
                        .HasColumnName("payout_configuration_version_snapshot");

                    b.Property<decimal>("PayoutMultiplierSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("payout_multiplier_snapshot");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)")
                        .HasColumnName("pool_id");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("selected_option");

                    b.Property<int>("Stake")
                        .HasColumnType("int")
                        .HasColumnName("stake");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PoolId");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<Guid?>("PredictionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("prediction_id");

                    b.Property<Guid>("SettlementRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("settlement_run_id");

                    b.HasKey("Id");

                    b.HasIndex("SettlementRunId");

                    b.ToTable("settlement_logs", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("settlement_runs", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedTournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_test_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("provider");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("sport");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedUserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutMarketRule", b =>
                {
                    b.HasOne("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutConfiguration", "PayoutConfiguration")
                        .WithMany("Rules")
                        .HasForeignKey("PayoutConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayoutConfiguration");
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementLog", b =>
                {
                    b.HasOne("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementRun", "SettlementRun")
                        .WithMany("Logs")
                        .HasForeignKey("SettlementRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementRun");
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedPayoutConfiguration", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("PoolPredict.Api.Infrastructure.Persistence.PersistedSettlementRun", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
